OrdererOrgs:
  - Name: Orderer
    Domain: example.com
    EnableNodeOUs: true
    Template:
      Count: 3
    Users:
      Count: 1

PeerOrgs:
  - Name: cbic
    Domain: cbic.example.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1

  - Name: port1
    Domain: port1.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: port2
    Domain: port2.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: port3
    Domain: port3.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: port4
    Domain: port4.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: gstn
    Domain: gstn.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: mha
    Domain: mha.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1