apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: scannr-ingress
  namespace: scannr
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
    nginx.ingress.kubernetes.io/rate-limit: "10000"
spec:
  tls:
  - hosts:
    - api.scannr.in
    - dashboard.scannr.in
    secretName: scannr-tls
  rules:
  - host: api.scannr.in
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: api-gateway
            port:
              number: 8000
  - host: dashboard.scannr.in
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dashboard-svc
            port:
              number: 8000
